title: WellsFLIX Systems Status Page
baseURL: https://status.wellsflix.com
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: WellsFLIX Status
      description: WellsFLIX Website
      link: https://www.wellsflix.com/
      group: Services
    - name: Plex
      description: Plex
      link: https://plex.wellsflix.com/web/index.html
      group: Services
    - name: Overseerr
      description: Overseerr
      link: https://overseerr.wellsflix.com
      group: Services
    - name: Unifi
      description: Unifi is the WellsFLIX Primary Router
      link: https://ui.wellsflix.com
      group: Network
    - name: Cloud
      description: WellsFLIX Cloud
      link: https://cloud.wellsflix.com/apps/dashboard/
      group: Services
    - name: XMission (ISP)
      group: Network
      description: XMission Provides WellsFLIX with Internet.
      link: https://status.xmission.com/
    - name: UTOPIA
      group: Network
      description: UTOPIA Provides the Backbone Fiber Connection to WellsFLIX
      link: https://twitter.com/utopia_status?lang=en
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " UTC"
  logo: /images/WellsFlix.png
  description_header: Information about <a class='text-grey-darkest' title='Visit
    www.wellsflix.com' href='https://www.wellsflix.com/'>WellsFLIX</a> systems
    operations.<br
  copyrightHolder: WellsFLIX Inc
  eventsPerPage: 10
  iconType: image/png
  groups:
    - Services
    - Network
  icon: /images/Logo.png
  description_footer: <a class='text-grey-darkest' title='Visit www.wellsflix.com'
    href='https://www.wellsflix.com/'>WellsFLIX.com</a> provides PLEX Media.
