title: WellsFLIX Systems Status Page
baseURL: https://status.wellsflix.com
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: WellsFLIX Status
      description: WellsFLIX Website
      link: https://www.wellsflix.com/
    - name: Plex
      description: Plex
      link: https://plex.wellsflix.com/web/index.html
    - name: Overseerr
      description: Overseerr
      link: https://overseerr.wellsflix.com
    - name: Unifi
      description: Unifi
      link: https://ui.wellsflix.com
    - name: Cloud
      description: WellsFLIX Cloud
      link: https://cloud.wellsflix.com/apps/dashboard/
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: America/Denver
  logo: /images/WellsFlix.png
  description_header: Information about <a class='text-grey-darkest' title='Visit
    www.wellsflix.com' href='https://www.wellsflix.com/'>WellsFLIX</a> systems
    operations.<br
  copyrightHolder: WellsFLIX Inc
  eventsPerPage: 10
  iconType: image/png
  icon: /images/Logo.png
  description_footer: <a class='text-grey-darkest' title='Visit www.wellsflix.com'
    href='https://www.wellsflix.com/'>WellsFLIX.com</a> provides PLEX Media.
